```mermaid
mindmap
  root((Moodle))
    data{{Remote Data}}
      CDATA / ODS
        ::icon(fa fa-server)
          PeopleSoft
            ::icon(fa fa-database)
          BI
            ::icon(fa fa-database)
      KeyCloak
        ::icon(fa fa-user-lock)
    servers{{Server Nodes}}
      web
      ::icon(fa fa-server)
        mysql
        ::icon(fa fa-database)
          ("db-backup")
          ::icon(fa fa-save)
        (cron)
        ::icon(fa fa-sync)
    tools{{Tools}}
      Admin Dashboard
      ::icon(fa fa-edit)
      Analytics
      ::icon(fa fa-chart-area)
      GitHub Project
      ::icon(fa fa-code-branch)
      Catalyst WRMS Tickets
      ::icon(fa fa-comments)
```