test -n "$BRANCH"
test -n "$BUILD_NAMESPACE"
echo "BUILIDING $DEPLOYMENT_NAME:$BRANCH"
  oc -n $BUILD_NAMESPACE process -f ./openshift/docker-build.yml \
    -p NAME=$DEPLOYMENT_NAME \
    -p PHP_IMAGE=$PHP_IMAGE \
    -p IMAGE_REPO=$IMAGE_REPO \
    -p IMAGE_NAME=$DEPLOYMENT_NAME \
    -p IMAGE_TAG=$BASE_IMAGE_TAG \
    -p SOURCE_REPOSITORY_URL=$SOURCE_REPOSITORY_URL \
    -p DOCKER_FILE_PATH=$DOCKER_FILE_PATH \
    -p PHP_INI_ENVIRONMENT=$PHP_INI_ENVIRONMENT \
    -p MOODLE_BRANCH_VERSION=$MOODLE_BRANCH_VERSION \
    -p F2F_BRANCH_VERSION=$F2F_BRANCH_VERSION \
    -p HVP_BRANCH_VERSION=$HVP_BRANCH_VERSION \
    -p FORMAT_BRANCH_VERSION=$FORMAT_BRANCH_VERSION \
    -p CERTIFICATE_BRANCH_VERSION=$CERTIFICATE_BRANCH_VERSION \
    -p CUSTOMCERT_BRANCH_VERSION=$CUSTOMCERT_BRANCH_VERSION \
    -p DATAFLOWS_BRANCH_VERSION=$DATAFLOWS_BRANCH_VERSION \
    -p SOURCE_CONTEXT_DIR=$SOURCE_CONTEXT_DIR | oc -n $BUILD_NAMESPACE apply -f -
oc -n $BUILD_NAMESPACE start-build bc/$DEPLOYMENT_NAME --commit=$BRANCH --no-cache --wait
