test -n "$BRANCH"
test -n "$BUILD_NAMESPACE"
echo "BUILIDING $PHP_DEPLOYMENT_NAME with tag: $BRANCH"
  oc -n $BUILD_NAMESPACE process -f ./openshift/docker-build.yml \
    -p NAME=$PHP_DEPLOYMENT_NAME \
    -p IMAGE_REPO=$IMAGE_REPO \
    -p IMAGE_NAME=$PHP_DEPLOYMENT_NAME \
    -p IMAGE_TAG=$BASE_IMAGE_TAG \
    -p SOURCE_REPOSITORY_URL=$SOURCE_REPOSITORY_URL \
    -p DOCKER_FILE_PATH=$PHP_DOCKER_FILE_PATH \
    -p SOURCE_CONTEXT_DIR=$PHP_SOURCE_CONTEXT_DIR | oc -n $BUILD_NAMESPACE apply -f -
oc -n $BUILD_NAMESPACE start-build bc/$PHP_DEPLOYMENT_NAME --commit=$BRANCH --no-cache --wait
