name: 🔨 Build and publish DB image to Artifactory

# concurrency:
#   group: ${{ github.ref }}
#   cancel-in-progress: true

env:
  APP: db
  USER: ${{ github.actor }}

on:
  workflow_call:
    secrets:
      ARTIFACTORY_URL:
        required: true
      ARTIFACTORY_USER:
        required: true
      ARTIFACTORY_PASSWORD:
        required: true

# on:
#   push:
#     branches:
#       - dev
#       #- test
#       #- prod
#     paths:
#       - '**/config/mariadb/**'
#       - '**/workflows/build-push-db-image.yml'
#   pull_request:
#     branches:
#       - dev
#       #- test
#       #- prod
#     paths:
#       - '**/config/mariadb/**'
#       - '**/workflows/build-push-db-image.yml'
jobs:
  #Print variables for logging and debugging purposes
  checkEnv:
    name: 📋 Environment Check
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check Env Vars
        run: |
          echo Building ${{ env.APP }}:${{ vars.OPENSHIFT_DEPLOY_PROJECT }}-${{ github.ref_name }}


  # # Build Images

  build-images:
    name: '🔨 Build DB image'
    needs: [checkEnv]
    runs-on: ubuntu-latest
    if: ${{ vars.SKIP_BUILD!= 'YES' }} && (github.ref_name == 'dev' || github.ref_name == 'test' || github.ref_name == 'prod')
    #if: ${{ needs.checkEnv.SKIP_BUILDS != 'YES' }} && (github.ref_name == 'dev' || github.ref_name == 'test' || github.ref_name == 'prod')
    steps:
      - name: 📤 Checkout Target Branch
        uses: actions/checkout@v2

      - name: Import env file
        id: dotenv
        uses: falti/dotenv-action@v1.1
        with:
          path: example.env

      # Login to Artifactory
      - name: 🔑 Login to Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACTORY_URL }}
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: 🛠️ Pull latest DB base image, tag, then push to Artifactory
        run: |
          docker pull ${{steps.dotenv.outputs.DB_IMAGE}}
          docker tag ${{steps.dotenv.outputs.DB_IMAGE}} ${{ secrets.ARTIFACTORY_URL }}/${{steps.dotenv.outputs.DB_IMAGE}}
          docker push ${{ secrets.ARTIFACTORY_URL }}/${{steps.dotenv.outputs.DB_IMAGE}}
